name: Hello
on:
    workflow_dispatch:
    # [push, pull_request]

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Helo World CI/CD"
            - uses: actions/checkout@v5